const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function setStatus(text,type=''){ $('status').textContent=text; $('dot').className='dot '+type; }
function domainOf(a){ if(a.domain)return a.domain.replace(/^www\./,''); try{return new URL(a.url).hostname.replace(/^www\./,'')}catch{return 'Fuente'} }
function fmtDate(s){ if(!s)return ''; const str=String(s); const m=str.match(/^(\d{4})(\d{2})(\d{2})T?(\d{2})?(\d{2})?/); if(m)return `${m[3]}/${m[2]}/${m[1]}${m[4]?' '+m[4]+':'+(m[5]||'00'):''}`; const d=new Date(str); return isNaN(d)?str:d.toLocaleString('es-AR',{dateStyle:'short',timeStyle:'short'}); }
function buildQuery(){ let q=$('q').value.trim(); if($('scope').value==='argentina') q += ' sourcecountry:argentina sourcelang:spanish'; return q.trim(); }
function gdeltUrl(){ const p=new URLSearchParams({query:buildQuery(),mode:'artlist',format:'json',maxrecords:'100',sort:'datedesc',timespan:$('span').value}); return 'https://api.gdeltproject.org/api/v2/doc/doc?'+p.toString(); }
function updateTrends(){ const term=$('q').value.trim(); const p=new URLSearchParams({q:term,geo:$('scope').value==='argentina'?'AR':''}); $('trends').href='https://trends.google.com/trends/explore?'+p.toString(); }
function renderMedia(arr){ const counts={}; arr.forEach(a=>{const d=domainOf(a); counts[d]=(counts[d]||0)+1}); const top=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,10); if(!top.length){$('media').innerHTML='<div class="empty"><strong>Sin fuentes</strong>No hay medios para contar.</div>';return} const max=top[0][1]; $('media').innerHTML=top.map(([d,n])=>`<div class="barrow"><div class="barlabel"><span>${esc(d)}</span><b>${n}</b></div><div class="bar"><span style="width:${Math.max(6,n/max*100)}%"></span></div></div>`).join(''); }
function render(arr){ $('m1').textContent=arr.length; $('m2').textContent=new Set(arr.map(domainOf)).size; $('m3').textContent=$('span').options[$('span').selectedIndex].text.replace('Últimas ','').replace('Último ',''); $('m4').textContent=arr.length?'OK':'0'; $('label').textContent=`${arr.length} resultados`; if(!arr.length){ $('articles').innerHTML='<div class="empty"><strong>No aparecieron noticias</strong>Probá ampliar el período o cambiar el término.</div>'; renderMedia(arr); return; } $('articles').innerHTML=arr.map(a=>`<div class="article"><h4><a href="${esc(a.url)}" target="_blank" rel="noopener">${esc(a.title||'Sin título')}</a></h4><div class="meta"><span class="media">${esc(domainOf(a))}</span><span>${esc(a.sourcecountry||'')}</span><span>${esc(fmtDate(a.seendate))}</span></div></div>`).join(''); renderMedia(arr); }
async function search(){ const term=$('q').value.trim(); if(!term){$('q').focus();return} updateTrends(); setStatus('Consultando GDELT…','load'); $('go').disabled=true; $('label').textContent='Cargando…'; $('diag').textContent='Intentando conexión directa desde la versión web.'; try{ const url=gdeltUrl(); const r=await fetch(url,{headers:{'Accept':'application/json'}}); if(!r.ok) throw new Error('GDELT respondió '+r.status); const data=await r.json(); const arr=Array.isArray(data.articles)?data.articles:[]; render(arr); $('diag').innerHTML=`Conexión correcta con GDELT. Consulta: <b>${esc(term)}</b>.`; setStatus(`Listo: ${arr.length} noticias.`,'ok'); }catch(e){ $('m1').textContent='—';$('m2').textContent='—';$('m4').textContent='ERROR'; $('articles').innerHTML=`<div class="empty"><strong>No pude traer resultados</strong>${esc(e.message)}</div>`; $('diag').innerHTML=`La página abrió correctamente, pero la consulta a GDELT falló: <b>${esc(e.message)}</b>. Esto ya nos permite diagnosticar el problema real.`; setStatus('La web funciona, pero falló la fuente de datos.','err'); }finally{$('go').disabled=false} }
$('go').onclick=search; $('q').addEventListener('keydown',e=>{if(e.key==='Enter')search()}); $('q').addEventListener('input',updateTrends); $('scope').addEventListener('change',updateTrends); updateTrends();