const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function setStatus(text,type=''){ $('status').textContent=text; $('dot').className='dot '+type; }
function fmtDate(s){ if(!s)return ''; const d=new Date(s); return isNaN(d)?String(s):d.toLocaleString('es-AR',{dateStyle:'short',timeStyle:'short'}); }
function sourceFromTitle(title){ const parts=String(title||'').split(' - '); return parts.length>1?parts[parts.length-1].trim():'Google News'; }
function cleanTitle(title){ const parts=String(title||'').split(' - '); return parts.length>1?parts.slice(0,-1).join(' - ').trim():String(title||'Sin título'); }
function domainFromUrl(url){ try{return new URL(url).hostname.replace(/^www\./,'')}catch{return ''} }
function articleSource(a){ return a.source||a.domain||sourceFromTitle(a.title)||domainFromUrl(a.url)||'Fuente'; }
function spanOperator(){ return ({'1d':'1d','3d':'3d','1w':'7d','1m':'30d'})[$('span').value]||'7d'; }
function baseTerm(){ return $('q').value.trim(); }
function googleNewsRss(){ let term=baseTerm(); if($('scope').value==='argentina') term += ' Argentina'; term += ` when:${spanOperator()}`; const p=new URLSearchParams({q:term,hl:'es-419',gl:'AR',ceid:'AR:es-419'}); return 'https://news.google.com/rss/search?'+p.toString(); }
function rss2jsonUrl(){ const p=new URLSearchParams({rss_url:googleNewsRss()}); return 'https://api.rss2json.com/v1/api.json?'+p.toString(); }
function gdeltQuery(){ let q=baseTerm(); if($('scope').value==='argentina') q += ' sourcecountry:argentina sourcelang:spanish'; return q.trim(); }
function gdeltUrl(){ const p=new URLSearchParams({query:gdeltQuery(),mode:'artlist',format:'json',maxrecords:'50',sort:'datedesc',timespan:$('span').value}); return 'https://api.gdeltproject.org/api/v2/doc/doc?'+p.toString(); }
function updateTrends(){ const term=baseTerm(); const p=new URLSearchParams({q:term,geo:$('scope').value==='argentina'?'AR':''}); $('trends').href='https://trends.google.com/trends/explore?'+p.toString(); }
async function fetchGoogle(){ const r=await fetch(rss2jsonUrl()); if(!r.ok) throw new Error('Google News/RSS2JSON respondió '+r.status); const data=await r.json(); if(data.status && data.status!=='ok') throw new Error(data.message||'RSS2JSON no pudo leer Google News'); const items=Array.isArray(data.items)?data.items:[]; return items.map(i=>({title:cleanTitle(i.title),url:i.link||i.guid,source:i.author||sourceFromTitle(i.title),date:i.pubDate,provider:'Google News'})).filter(a=>a.url); }
async function fetchGdelt(){ const r=await fetch(gdeltUrl(),{headers:{'Accept':'application/json'}}); if(!r.ok) throw new Error('GDELT respondió '+r.status); const data=await r.json(); const items=Array.isArray(data.articles)?data.articles:[]; return items.map(i=>({title:i.title||'Sin título',url:i.url,source:i.domain||'',date:i.seendate,provider:'GDELT'})).filter(a=>a.url); }
function dedupe(arr){ const seen=new Set(); return arr.filter(a=>{ const key=(a.title||a.url).toLowerCase().replace(/\s+/g,' ').trim(); if(seen.has(key))return false; seen.add(key); return true; }); }
function renderMedia(arr){ const counts={}; arr.forEach(a=>{const d=articleSource(a); counts[d]=(counts[d]||0)+1}); const top=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,10); if(!top.length){$('media').innerHTML='<div class="empty"><strong>Sin fuentes</strong>No hay medios para contar.</div>';return} const max=top[0][1]; $('media').innerHTML=top.map(([d,n])=>`<div class="barrow"><div class="barlabel"><span>${esc(d)}</span><b>${n}</b></div><div class="bar"><span style="width:${Math.max(6,n/max*100)}%"></span></div></div>`).join(''); }
function render(arr,googleCount,gdeltCount){ $('m1').textContent=arr.length; $('m2').textContent=new Set(arr.map(articleSource)).size; $('m3').textContent=$('span').options[$('span').selectedIndex].text.replace('Últimas ','').replace('Último ',''); $('m4').textContent=googleCount?`G ${googleCount}`:(gdeltCount?`D ${gdeltCount}`:'0'); $('label').textContent=`${arr.length} resultados`; if(!arr.length){ $('articles').innerHTML='<div class="empty"><strong>No aparecieron noticias</strong>Probá ampliar el período o cambiar el término.</div>'; renderMedia(arr); return; } $('articles').innerHTML=arr.map(a=>`<div class="article"><h4><a href="${esc(a.url)}" target="_blank" rel="noopener">${esc(a.title||'Sin título')}</a></h4><div class="meta"><span class="media">${esc(articleSource(a))}</span><span>${esc(a.provider||'')}</span><span>${esc(fmtDate(a.date))}</span></div></div>`).join(''); renderMedia(arr); }
async function search(){ const term=baseTerm(); if(!term){$('q').focus();return} updateTrends(); setStatus('Buscando en Google News y GDELT…','load'); $('go').disabled=true; $('label').textContent='Cargando…'; $('diag').textContent='Consultando dos fuentes gratuitas.'; let google=[],gdelt=[],errors=[]; try{ try{google=await fetchGoogle()}catch(e){errors.push('Google News: '+e.message)} try{gdelt=await fetchGdelt()}catch(e){errors.push('GDELT: '+e.message)} const all=dedupe([...google,...gdelt]); render(all,google.length,gdelt.length); if(all.length){ $('diag').innerHTML=`Google News: <b>${google.length}</b> resultados. GDELT: <b>${gdelt.length}</b> resultados.${errors.length?'<br>'+esc(errors.join(' · ')):''}`; setStatus(`Listo: ${all.length} noticias.`,'ok'); } else { throw new Error(errors.join(' · ')||'Las fuentes respondieron sin resultados'); } }catch(e){ $('m1').textContent='—';$('m2').textContent='—';$('m4').textContent='ERROR'; $('articles').innerHTML=`<div class="empty"><strong>No pude traer resultados</strong>${esc(e.message)}</div>`; $('diag').innerHTML=`Fallaron las fuentes de datos: <b>${esc(e.message)}</b>.`; setStatus('La web funciona, pero las fuentes no respondieron.','err'); }finally{$('go').disabled=false} }
$('go').onclick=search; $('q').addEventListener('keydown',e=>{if(e.key==='Enter')search()}); $('q').addEventListener('input',updateTrends); $('scope').addEventListener('change',updateTrends); updateTrends();