const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function setStatus(text,type=''){ $('status').textContent=text; $('dot').className='dot '+type; }
function fmtDate(s){ if(!s)return ''; const d=new Date(s); return isNaN(d)?String(s):d.toLocaleString('es-AR',{dateStyle:'short',timeStyle:'short'}); }
function domainFromUrl(url){ try{return new URL(url).hostname.replace(/^www\./,'')}catch{return ''} }
function articleSource(a){ return a.source||domainFromUrl(a.url)||'Fuente'; }
function baseTerm(){ return $('q').value.trim(); }
function newsUrl(){ const p=new URLSearchParams({q:baseTerm(),scope:$('scope').value,span:$('span').value}); return '/api/news?'+p.toString(); }
function updateTrends(){ const p=new URLSearchParams({q:baseTerm(),geo:$('scope').value==='argentina'?'AR':''}); $('trends').href='https://trends.google.com/trends/explore?'+p.toString(); }
async function fetchNews(){ const r=await fetch(newsUrl(),{headers:{Accept:'application/json'}}); const data=await r.json().catch(()=>({error:'Respuesta inválida del backend'})); if(!r.ok) throw data; return data; }
function dedupe(arr){ const seen=new Set(); return arr.filter(a=>{const k=(a.title||a.url).toLowerCase().replace(/\s+/g,' ').trim(); if(seen.has(k))return false; seen.add(k); return true;}); }
function renderMedia(arr){ const counts={}; arr.forEach(a=>{const d=articleSource(a);counts[d]=(counts[d]||0)+1}); const top=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,10); if(!top.length){$('media').innerHTML='<div class="empty"><strong>Sin fuentes</strong>No hay medios para contar.</div>';return} const max=top[0][1]; $('media').innerHTML=top.map(([d,n])=>`<div class="barrow"><div class="barlabel"><span>${esc(d)}</span><b>${n}</b></div><div class="bar"><span style="width:${Math.max(6,n/max*100)}%"></span></div></div>`).join(''); }
function render(arr){ $('m1').textContent=arr.length; $('m2').textContent=new Set(arr.map(articleSource)).size; $('m3').textContent=$('span').options[$('span').selectedIndex].text.replace('Últimas ','').replace('Último ',''); const active=[...new Set(arr.map(a=>a.provider).filter(Boolean))]; $('m4').textContent=active.length; $('m4sub').textContent=active.join(' + ')||'sin fuentes'; $('label').textContent=`${arr.length} resultados`; $('articles').innerHTML=arr.length?arr.map(a=>`<div class="article"><h4><a href="${esc(a.url)}" target="_blank" rel="noopener">${esc(a.title||'Sin título')}</a></h4><div class="meta"><span class="media">${esc(articleSource(a))}</span><span>${esc(a.provider||'')}</span><span>${esc(fmtDate(a.date))}</span></div></div>`).join(''):'<div class="empty"><strong>No aparecieron noticias</strong>Probá ampliar el período o cambiar el término.</div>'; renderMedia(arr); }
function sourceLine(name,x={}){ if(x.ok)return `<div><b style="color:var(--accent)">● ${esc(name)}</b> · ${x.count||0} resultados</div>`; return `<div style="opacity:.62"><b>○ ${esc(name)}</b> · no disponible${x.error?` · ${esc(String(x.error).slice(0,120))}`:''}</div>`; }
function diag(d={}){ return `${sourceLine('Bing News',d.bingNews)}${sourceLine('GDELT',d.gdelt)}${sourceLine('Google News',d.googleNews)}`; }
async function search(){ const term=baseTerm(); if(!term){$('q').focus();return} updateTrends(); setStatus('Buscando noticias…','load'); $('go').disabled=true; $('label').textContent='Cargando…'; $('diag').textContent='Consultando fuentes abiertas desde StonedOwl.'; try{ const data=await fetchNews(); const all=dedupe(data.articles||[]); render(all); $('diag').innerHTML=diag(data.diagnostics); if(all.length){ setStatus(`Listo: ${all.length} noticias reales.`,'ok'); } else { setStatus('Las fuentes respondieron, pero no hubo resultados.',''); } }catch(e){ $('m1').textContent='—';$('m2').textContent='—';$('m4').textContent='0';$('m4sub').textContent='sin fuentes'; $('articles').innerHTML=`<div class="empty"><strong>No pude traer resultados</strong>${esc(e.error||'Error de fuentes')}</div>`; $('diag').innerHTML=(e.error?esc(e.error)+'<br>':'')+diag(e.diagnostics); setStatus('No hubo ninguna fuente disponible.','err'); }finally{$('go').disabled=false} }
$('go').onclick=search; $('q').addEventListener('keydown',e=>{if(e.key==='Enter')search()}); $('q').addEventListener('input',updateTrends); $('scope').addEventListener('change',updateTrends); updateTrends();
