import assert from 'node:assert/strict';
import { buildEditorialCases } from '../data/editorial-cases.js';
const now = Date.parse('2026-10-08T09:03:16Z');
const article = { title: 'Almagro vivió la despedida de Messi entre festejos ...', snippet: 'Según EDESUR había 38 usuarios de Almagro sin suministro eléctrico.', source: 'revistaelabasto.com.ar', url: 'https://www.revistaelabasto.com.ar/almagro-vivio-la-despedida-de-messi-entre-festejos-bocinas-y-un-corte-de-luz/', date: 'hace 17 horas' };
const evaluations = [{ article, classification: { acceptedForBarrio: false, reasonCodes: ['no_meaningful_electric_signal'] } }];
const cases = buildEditorialCases({ evaluations, now });
assert.equal(cases.length, 1);
assert.equal(cases[0].evidenceStatus, 'por_verificar');
assert.deepEqual(cases[0].barrios, ['Almagro']);
assert.equal(cases[0].responsibility.government, null);
assert.equal(cases[0].readyToPublish, false);
assert.equal(cases[0].trend, 'no_evaluada');
assert.equal(buildEditorialCases({evaluations: [...evaluations,...evaluations], now}).length, 1);
assert.equal(buildEditorialCases({evaluations: [{article:{...article,date:''}, classification:{}}], now}).length, 0);
assert.equal(buildEditorialCases({evaluations: [{article, classification:{reasonCodes:['commercial_result']}}], now}).length, 0);
assert.equal(buildEditorialCases({signals:[{...article,url:'javascript:alert(1)'}], now}).length, 0);
const single = buildEditorialCases({signals:[{...article,barrios:[{name:'Almagro'}]}], now});
assert.equal(single[0].evidenceStatus, 'fuente_identificada');
const official = buildEditorialCases({signals:[{...article,company:'EDESUR',official:true,enreType:'programado',affectedUsers:330,barrio:'Flores'}],now});
assert.equal(official[0].eventType, 'programado');
assert.equal(official[0].responsibility.operator, 'EDESUR');
assert.match(official[0].question,/plazo anunciado/);
console.log('Editorial cases: single-source case visible, rejected Almagro lead recovered, uncertainty retained, duplicates and unsafe links excluded.');
